name: smartbugs

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install Python + jq (Docker already exists on runner)
      - name: Install minimal deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv jq

      - name: Show Docker version (preinstalled on runner)
        run: |
          docker version
          docker info

      - name: Fetch SmartBugs
        run: |
          git clone --depth 1 https://github.com/smartbugs/smartbugs
          cd smartbugs
          python3 -m venv venv
          . venv/bin/activate
          # detect runner Python version (e.g., 3.12)
          PYVER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
          REQFILE="install/requirements-$PYVER.txt"
          echo "Using $REQFILE"
          pip install -r "$REQFILE"

      - name: Run SmartBugs (Slither + Mythril + Semgrep) on contracts
        working-directory: smartbugs
        env:
          DOCKER_BUILDKIT: 0
        run: |
          . venv/bin/activate
          # Run each tool separately to avoid configuration issues
          ./smartbugs -t slither -f ../contracts/*.sol --timeout 600 --sarif --runid github-slither
          ./smartbugs -t mythril -f ../contracts/*.sol --timeout 600 --sarif --runid github-mythril  
          ./smartbugs -t semgrep -f ../contracts/*.sol --timeout 600 --sarif --runid github-semgrep
          mkdir -p ../sarif
          find results -name "*.sarif" -exec cp {} ../sarif/ \;

      # ✅ Debug step to check SARIF files
      - name: Debug SARIF output
        run: |
          echo "=== SARIF files generated ==="
          ls -lh sarif || true
          for f in sarif/*.sarif; do
            echo "---- $f ----"
            head -n 50 $f || true
          done

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif/
