name: Smart Contract CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Hardhat Tests
        run: npx hardhat test

  security:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Solhint
        run: npm install -g solhint

      - name: Run Solhint linting
        run: |
          echo "=== SOLHINT SECURITY ANALYSIS ===" | tee security-report.txt
          echo "Tool: Solhint" | tee -a security-report.txt
          echo "Timestamp: $(date)" | tee -a security-report.txt
          echo "" | tee -a security-report.txt
          npx solhint "contracts/**/*.sol" --formatter=unix | tee -a security-report.txt

      - name: Install Slither
        run: |
          pip install slither-analyzer
          
          # Verify Slither installation
          echo "Verifying Slither installation..." | tee security-report.txt
          slither --version | tee -a security-report.txt || echo "Slither not found in PATH" | tee -a security-report.txt
          
          # Check current directory and contract status
          echo "" | tee -a security-report.txt
          echo "Current directory: $(pwd)" | tee -a security-report.txt
          echo "Contract files:" | tee -a security-report.txt
          ls -la contracts/ | tee -a security-report.txt
          echo "" | tee -a security-report.txt
          
          echo "=== SLITHER SECURITY ANALYSIS ===" | tee -a security-report.txt
          echo "Tool: Slither" | tee -a security-report.txt
          echo "Timestamp: $(date)" | tee -a security-report.txt
          echo "" | tee -a security-report.txt
          
          # Run Slither with simple command first
          slither . --print human-summary 2>&1 | tee -a security-report.txt || echo "Slither command failed, trying alternative approach..."
          
          # If first command failed, try with different options
          if ! grep -q "SLITHER SECURITY ANALYSIS" security-report.txt || ! grep -q "slither" security-report.txt; then
            echo "" | tee -a security-report.txt
            echo "Trying alternative Slither command..." | tee -a security-report.txt
            slither . 2>&1 | tee -a security-report.txt || echo "Slither analysis failed"
          fi

      - name: Upload full security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [build, security]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Deploy to Sepolia Testnet
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: npx hardhat run scripts/deploy.js --network sepolia

      - name: Verify Contract on Etherscan
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          # This will be updated with the actual deployed contract address
          echo "Contract verification step - update with actual address"
          # npx hardhat verify --network sepolia DEPLOYED_CONTRACT_ADDRESS 