name: smartbugs
on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write   # required for SARIF upload
  actions: read

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install minimal deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv jq

      - name: Fetch SmartBugs
        run: |
          git clone --depth 1 https://github.com/smartbugs/smartbugs
          cd smartbugs
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      # 👉 Adjust the glob to where your .sol files actually live
      - name: Run SmartBugs (Slither + Mythril + Semgrep)
        working-directory: smartbugs
        run: |
          set -euxo pipefail
          . .venv/bin/activate
          mkdir -p ../sarif

          # Run SmartBugs and request SARIF outputs
          # (if your version doesn't support --sarif directly, SmartBugs will still
          # create tool-specific SARIF in results/; we’ll collect them below)
          ./smartbugs -t slither,mythril,semgrep -f ../contracts/**/*.sol --timeout 600 --sarif || true

          echo "=== Collect SARIF files into ../sarif ==="
          # SmartBugs writes into ./results/<tool>/<contract>.sarif
          find results -type f -name "*.sarif" -print -exec cp {} ../sarif/ \;

          echo "=== Short listing of collected SARIF ==="
          ls -lh ../sarif || true
          for f in ../sarif/*.sarif; do
            echo "---- $f ----"
            head -n 25 "$f" || true
          done

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          # You can point to a directory; the action will ingest all SARIF files in it
          sarif_file: sarif

      # Optional but super helpful for debugging / offline viewing
      - name: Upload SmartBugs raw results (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: smartbugs-results
          path: |
            smartbugs/results
            sarif
