name: smartbugs

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write   # needed to upload SARIF to GitHub code scanning

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      # Optional: cache Docker layers for faster SmartBugs runs
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv jq docker.io

      - name: Fetch SmartBugs
        run: |
          git clone --depth 1 https://github.com/smartbugs/smartbugs
          cd smartbugs
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Run SmartBugs (Slither + Mythril + Semgrep) on contracts
        working-directory: smartbugs
        run: |
          . .venv/bin/activate
          # adjust the glob path to your contracts
          ./smartbugs -t slither,mythril,semgrep -f ../contracts/*.sol --timeout 600 --sarif --runid github
          mkdir -p ../sarif
          find results -name "*.sarif" -exec cp {} ../sarif/ \;

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif
